version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:

  pre_build:
    commands:
      - echo "Source path:" $SOURCE_PATH
      - cd $SOURCE_PATH/src
      - pip install --target ./package -r requirements.txt
  build:
    commands:
      - cp *.py ./package
  post_build:
    commands:

artifacts:
  files:
    - "**/*"
  base-directory: "$SOURCE_PATH/src/package"
  discard-paths: no
